version: '3'
services:
  generator:
    build: ./generator
    ports:
      - "8001:8000"
  invoker:
    build: ./invoker
    ports:
      - "8002:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
